### ISSUE TITLE
Intro to pandas: baseball table shape

### ISSUE THREAD

**Issue by timozattol** [ADAEPFL/Labs#7]
In the intro to pandas, there is:
```python
baseball.shape
baseball.drop([89525, 89526])
baseball.drop(['ibb','hbp'], axis=1)
```

Maybe it would be cleaner to have:
```python
baseball.shape
baseball.drop([89525, 89526]).shape #shape added
baseball.drop(['ibb','hbp'], axis=1).shape #shape added
```

Else the whole table prints and it isn't easy to see the difference :)

**Comment by pirroh** [comment]
Thanks for the feedback, @timozattol !
I see your point, but those rows and columns have been selected in such a way that when you print the whole dataframe, you can easily figure out that they disappeared (because they occur at the end of the DF). Printing the shape definitely helps, but it doesn't show you explicitly what has been dropped :)
